### PR TITLE
Upated build system for MacOS X 10.9.5

### PR DESCRIPTION
**Pull request by aerlaut**
Added build system for MacOS X 10.9.5.

### CODE REVIEW

**Comment by nathanielw** [comment]
Just tried this out on 10.10 and there seems to be a few things still not working with the build script. I've created a patch at https://gist.github.com/nathanielw/7154124035bc3249bab1 with what I had to change to get it building for me. Just a few minor changes and Pencil is building and running fine :smiley:

**Comment by aerlaut** [comment]
Proposed patch changes added and tested on OS X 10.9.5. Builds fine :+1:

**Comment by prikhi** [comment]
Heya, I've been away for a while so I've got a backlog of stuff in all my projects, just quickly checking in so you know you're not being ignored. I will review & merge this soon-ish.

**Comment by aerlaut** [comment]
Thanks :)

**Comment by prikhi** [comment]
How should I package the folder for downloading? Is a zip OK? Or rar, tar?

I'd like to add install directions to the readme. How does one go about installing the downloaded file(maybe this is obvious for Mac users)?

Otherwise, looks good thanks :)

**Comment by prikhi** [comment]
I merged this but rebased it so github doesn't want to acknowledge it :/

**Comment by aerlaut** [comment]
Hi,

Just zip the .app File. Mac users will then extract it and just copy it to the Application directory.

Cheers,
aerlaut

Sent from my Windows Phone

**Pull request closed without merging**
