### PR TITLE
Feature/deb package

### PR DESCRIPTION
**Pull request by ReadyPlayerNaN**
Hi, this creates Ubuntu deb file. I didn't test it on Debian, but it should work there as well.

### CODE REVIEW

**Comment by prikhi** [comment]
Thanks a lot! I'm about to go out of town for 2 weeks & I might not have time to review this before then.

**Comment by Mte90** [comment]
+1

**Comment by prikhi** [comment]
Thanks, will release a new version with a .deb soon.

The `sudo chown -R root ...` line isn't necessary is it? It causes an error for me & everything seems fine with it removed.

**Comment by ReadyPlayerNaN** [comment]
@prikhi, a month ago, I would know. I guess that deb package files keep their ownership when you install them and you want root owned files in your /usr. The error it caused you was probably 'Operation not permitted', right? You can't just change ownership like a regular user.

_Should have documented that. Should have documented that._

**Comment by prikhi** [comment]
On Mon, Sep 21, 2015 at 12:51:13AM -0700, Pavel Žák wrote:

> @prikhi, a month ago, I would know. I guess that deb package files
> keep their ownership when you install them and you want root owned
> files in your /usr. The error it caused you was probably 'Operation
> not permitted', right? You can't just change ownership like a regular
> user.
> 
> _Should have documented that. Should have documented that._
> Did a quick search, looks like you're right, permissions are retained.
> I've added it back in with a sudo call & use the sudo privileges to
> clean up build dir afterwards.

Thanks for the patch, sorry for the delay.

**Comment by ReadyPlayerNaN** [comment]
Thank you for maintaining it :)

Are you going to maintain it in Ubuntu package repositories?

**Pull request merged**
