### PR TITLE
Increase the required Firefox version

### PR DESCRIPTION
**Pull request by mvdw**
When running pencil on the linux command line, I got:

   Error: Platform version '39.0' is not compatible with 
   minVersion >= 36.0
   maxVersion <= 38.*

Instead of increasing the maxVersion to 39, it is better to put it on 100 or so - this way we do not have to update it all the time.

### CODE REVIEW

**Comment by mvdw** [comment]
BTW, why is the minVersion increased to 36.0? 
In the original evolus version is was much lower...
I have a system here with version 17.0.10 and it works perfectly with Pencil (after adapting the minVersion). So, I propose to lower the minVersion to something like 17.0.

**Comment by prikhi** [comment]
I've kept the maxVersion to a version someone's tested Pencil on because I'm kinda paranoid of a backwards incompatible change destroying saved data... Maybe that's too paranoid?

Do PNG exports work in v17? I believe this change in FF36 broke them:

> The nsIWebBrowserPersist.saveURI() method now requires 8 arguments, in an order incompatible with previous releases.

https://developer.mozilla.org/en-US/Firefox/Releases/36

**Comment by mvdw** [comment]
I believe the version 17.0.10 was the xulrunner version.
On my laptop I have (openSuse 13.2 and) now updated xulrunner to the latest version: 31.8.0.

That means, that when I install the latest Pencil 2.0.12, I get the error:
Platform version 31.8.0 is not compatible with:
minVersion >= 36.0
maxVersion <= 39.*

The simplest solution IMHO would be to lower the minVersion (to 31 or 17, at your wish).

**Comment by mvdw** [comment]
Hmm, on second thought: There are multiple problems here:
- if xulrunner is installed, then the max/minVersions apply to the xulrunner versions, if xulrunner is not installed, then the versions apply to firefox.
- the moment that firefox chooses to update my system to firefox 40, my pencil install will cease to start at all. Then I have to wait until the package creator updates the pencil package, and then I have to install that. This is an impossible situation - we can not do this to our users. 
- if firefox 36 was the only version that broke Pencil, then we should have only that version be excluded. Maybe just show a warning to the user - but I would not advise to attempt that - to complicated.
- I am working on updating the openSuse package from 2.05 to 2.012. It already works, but this version problem makes Pencil unusable when also xulrunner is installed. That is unacceptable.

Conclusion: quick and dirty fix please: reduce the minVersion. Ofcourse, I can include a patch in the rpm build...

**Comment by mvdw** [comment]
I have been reading the XUL Application Packaging instructions at https://developer.mozilla.org/en-US/docs/XUL_Application_Packaging. It says: 

```
The [Gecko] section
The Gecko section specifies what version of XULRunner is required by the application.
MinVersion
    Specifies the minimum XULRunner version needed by this application. If there are binary components, MinVersion must equal the version of the libxul SDK which is used to build the application.
    REQUIRED
    Example: MinVersion=1.8
MaxVersion
    Specify the maximum XULRunner version needed by this application.
    OPTIONAL - default value is any XULRunner less than XULRunner 2
    Example: MaxVersion=1.8.0.* 
```

My conclusion: This system is broken.
Apparently, when running an application, the given values are compared to the firefox or xulrunner versions, NOT the Gecko version.

The following link is a book:
https://books.google.be/books?isbn=1304608700
This book advises on page 11 to set the max version on 200.*, or package the right xulrunner with the app.
I advise to do the former for Linux, and the latter for Windows.

**Comment by prikhi** [comment]
FF36 made us make a change that breaks the app for every previous version of FF. If you try exporting a document as a PNG with a version before FF36 it will just hang. I think all export methods might've been broken by this. I think it's a good idea to keep it at 36.

I'm running FF's dev release now so I'll at least keep the maxversion at that version number(currently 41), maybe bump it up to 200 or something.

Windows builds have xulrunner packaged with them already.

If openSUSE's xulrunner is that old, I'd run a `sed` command when packaging that removes `xulrunner` from the `BINARIES` array in `/bin/pencil`(assuming opensuse's packaging system allows this) & then make the package depend on Firefox instead of xulrunner. That'll make sure it uses FF to launch instead of xulrunner.

**Comment by rodfersou** [comment]
need  to rebase before accept this pull request

**Comment by mvdw** [comment]
I did use the sed command as described above. There is no problem any more on OpenSUSE.
This request may be closed now.

**Pull request closed without merging**
